image: alpine:latest

pages:
  stage: deploy
  before_script:
    - mkdir -p public
    - find . -maxdepth 1 -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" \) -exec cp {} public/ \;
    - ls -la public/
  script:
    - echo "Prepared public/ for GitLab Pages deployment"
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
